version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - PORT=8000
      - ENV_FILE_PATH=./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: >
      bash -c "bandit -r . && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend_prod
    volumes:
      # - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: ["pnpm", "start"]
    env_file:
      - ./frontend/.env.production
